### ISSUE TITLE
Cypress Testing for Ribbon plugin

### ISSUE THREAD

**Issue by chrisllontop** [regolith-code/Aloha-Editor#36]
## Testing scenarios

- [x] Testing on ribbon bar on top of the page
- [ ] Testing on multiple add-ons

**Comment by JwanCortez93** [comment]
@christianllv 

The testing for this one is kinda weird, because it all depends on a different .js, since the ribbon is made externally. The ribbon appears fine and it works. I could test the rest with an example, but the menu items in the .js don't have id, so I need help understanding how to set them up.
